version: "3.8"

services:
  wp:
    container_name: wordpress_cabinets-plus
    image: wordpress:6.1.1-php7.4-apache
    ports:
      - :${WP_PORT}:80
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html

    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: "${WP_DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${WP_DB_ROOT_PASSWORD}"
    depends_on:
      - mysql
    links:
      - mysql

  pma:
    container_name: pma_cabinets-plus
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${WP_DB_ROOT_PASSWORD}"
      UPLOAD_LIMIT: 50M
    ports:
      - :8080:80
    links:
      - mysql:mysql

  mysql:
    container_name: mysql_cabinets-plus
    image: mysql:latest
    ports:
      - 3306:3306
    command:
      [
        "--default_authentication_plugin=mysql_native_password",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${WP_DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${WP_DB_ROOT_PASSWORD}"

volumes:
  db_data:
